SELECT DISTINCT
	(CASE
		WHEN MNF.NRO_MANIFESTO IS NULL THEN 'SEM VIAGEM'
		WHEN MNF.DT_CHEGADA IS NULL THEN 'EM VIAGEM'
	ELSE
		'EM TRANSBORDO'
	END) AS STATUS_MOVIMENTO

	,MNF.NRO_MANIFESTO
	,MNF.DT_EMISSAO_MANIFESTO
	,MNF.DT_CHEGADA
	,MNF.DT_BAIXA
	,MNF.FIL_BAIXA_MNF
	,MNF.NOME_PROP
	,MNF.COD_DADOS_MANIFESTO_CUSTO_EMIS
	,MONFCLMNF.*
FROM
	( SELECT DISTINCT 
		SAC.nm_usuario AS ATENDENTE
		,(CASE
			WHEN MONFCL.ESTADO_DEST IN ('DF','GO','MS','MT') THEN 'Centro-Oeste' 
			WHEN MONFCL.ESTADO_DEST IN ('AL','BA','CE','MA','PB','PE','PI','RN','SE') THEN 'Nordeste' 
			WHEN MONFCL.ESTADO_DEST IN ('AC','AM','AP','PA','RO','RR','TO') THEN 'Norte' 
			WHEN MONFCL.ESTADO_DEST IN ('ES','MG','RJ','SP') THEN 'Sudeste' 
			WHEN MONFCL.ESTADO_DEST IN ('PR','RS','SC') THEN 'Sul' 
		END) AS REGIAO
		,(CASE
			WHEN MONFCL.DIAS_OCORRENCIA BETWEEN  0 AND 3 THEN '1 A 3'
			WHEN MONFCL.DIAS_OCORRENCIA BETWEEN  4 AND 6 THEN '4 A 6'
			WHEN MONFCL.DIAS_OCORRENCIA BETWEEN  7 AND 15 THEN '7 A 15'
			WHEN MONFCL.DIAS_OCORRENCIA BETWEEN  16 AND 30 THEN '16 A 30'
			WHEN MONFCL.DIAS_OCORRENCIA >30 THEN ' > 30'
			WHEN MONFCL.DIAS_OCORRENCIA = 0 THEN 'HOJE'
		ELSE 'SEM OCORRENCIA'
		END) AS FAIXA_OCORRENCIA

		,(CASE
			WHEN MONFCL.DIAS_ATRASO BETWEEN  1 AND 3 THEN '1 A 3'
			WHEN MONFCL.DIAS_ATRASO BETWEEN  4 AND 6 THEN '4 A 6'
			WHEN MONFCL.DIAS_ATRASO BETWEEN  7 AND 15 THEN '7 A 15'
			WHEN MONFCL.DIAS_ATRASO BETWEEN  16 AND 30 THEN '16 A 30'
			WHEN MONFCL.DIAS_ATRASO >30 THEN ' > 30'
			WHEN MONFCL.DIAS_ATRASO = -1 THEN 'AMANHÃ'
			WHEN MONFCL.DIAS_ATRASO = 0 THEN 'HOJE'
		ELSE 'NO PRAZO'
		END) AS FAIXA_ATRASO
		
			  
	
			  ,NFS.COD_SOLID_NFS_CTES
			  ,NFS.NUM_NOTA_FISCAL AS NF
			  ,NFS.SERIE
			  ,NFS.VOLUMES
			  ,NFS.PESO
			  ,NFS.ITEM
			  ,NFS.CHAVE_ACESSO_NFE
			  ,NFS.DT_EMISS_NF
			  ,NFS.NR_RECEPCAO
			  ,NFS.DT_RECEPCAO
			  ,NFS.DT_CAR
			  ,NFS.DT_DESCAR
			  ,NFS.NR_PEDIDO_ENTREGA
			  ,NFS.NR_EMBARQUE

			  ,MONFCL.CLIENTE_GRUPO 
			  ,MONFCL.STATUS_ENTREGA
			  ,MONFCL.ATUALIZACAO_PAINEL
			  ,MONFCL.DATA_OCORRENCIA
			  ,MONFCL.ACOMPANHAMENTO
			  ,MONFCL.CODIGO_OCOR
			  ,MONFCL.DESCRICAO_OCOR
			  ,MONFCL.RESPONSABILIDADE
			  ,MONFCL.DIAS_ATRASO
			  ,MONFCL.DIAS_OCORRENCIA

			  ,MONFCL.COD_DADOS_MOVIMENTO_CUSTO_EMIS
			  ,MONFCL.SIGLA_FIL
			  ,MONFCL.NR_ENTRADA
			  ,MONFCL.NUM_DOC
			  ,MONFCL.TIPO_FRETE
			  ,MONFCL.TIPO_DOC
			  ,MONFCL.SERIE_DOC
			  ,MONFCL.RT1
			  ,MONFCL.RT2
			  ,MONFCL.RT3
			  ,(CASE
				 WHEN MONFCL.RT4 IN ('I','C') THEN MONFCL.RT4 ELSE 'I2' 
			   END)
			  ,MONFCL.CIDADE
			  ,MONFCL.ESTADO
			  ,MONFCL.CIDADE_DESTINO
			  ,MONFCL.ESTADO_DESTINO
			  ,MONFCL.REMETENTE
			  ,MONFCL.DESTINATARIO
			  ,MONFCL.CONSIGNATARIO
			  ,MONFCL.CGC_CONSIG
			  ,MONFCL.CGC_REMET
			  ,MONFCL.CGC_DEST
			  ,MONFCL.VENDEDOR
			  ,MONFCL.FATOR_CONVERSAO_CLIENTE
			  ,MONFCL.FATOR_CONVERSAO_PADRAO
			  ,MONFCL.FIL_RESP_FRETE
			  ,MONFCL.NR_COLETA
			  ,MONFCL.DT_EMISSAO
			  ,MONFCL.DT_ENTREGA
			  ,MONFCL.DT_ATUALIZADO
			  ,MONFCL.PREVISAO_ENTREGA
			  ,MONFCL.DESCR_TIPO_TRANSP
			  ,MONFCL.DATA_COLETA
			  ,MONFCL.SIGLA_FIL_DEST
			  ,MONFCL.CODIGO_ROTA_ENTREGA
			  ,MONFCL.TIPO_TAB
			  ,MONFCL.ENDERECO_DEST
			  ,MONFCL.CIDADE_DEST
			  ,MONFCL.ESTADO_DEST
			  ,MONFCL.BAIRRO_DEST
			  ,MONFCL.CEP_DEST
			  ,MONFCL.LOCAL_ENTREGA

			  FROM 
		( SELECT  DISTINCT
			 ( CASE 
				WHEN CL.DESCR_GRUPO_CLIENTE = '' THEN MONF.CONSIGNATARIO 
				WHEN CL.DESCR_GRUPO_CLIENTE IS NULL THEN MONF.CONSIGNATARIO 
				ELSE
				CL.DESCR_GRUPO_CLIENTE
			  END) AS CLIENTE_GRUPO

			, (DATEDIFF(dd,MONF.DATA_OCORRENCIA ,  GETDATE())) 
				-(DATEDIFF(wk, MONF.DATA_OCORRENCIA,  GETDATE()) * 2) 
				-(CASE WHEN DATEPART(dw,  GETDATE()) = 1 THEN 1 ELSE 0 END) 
				-(CASE WHEN DATEPART(dw,  GETDATE()) = 7 THEN 1 ELSE 0 END) 	
			  as DIAS_OCORRENCIA

			, (DATEDIFF(dd,MONF.PREVISAO_ENTREGA ,  GETDATE())) 
				-(DATEDIFF(wk, MONF.PREVISAO_ENTREGA,  GETDATE()) * 2) 
				-(CASE WHEN DATEPART(dw,  GETDATE()) = 1 THEN 1 ELSE 0 END) 
				-(CASE WHEN DATEPART(dw,  GETDATE()) = 7 THEN 1 ELSE 0 END) 	
			  as DIAS_ATRASO

			, (CASE WHEN (DATEDIFF(dd,MONF.PREVISAO_ENTREGA ,  GETDATE()) ) <= 0 THEN 'EM_ABERTO'  ELSE 'EM_ATRASO' END) AS STATUS_ENTREGA

			, GETDATE() AS ATUALIZACAO_PAINEL

			,MONF.* 

				FROM  
				(
					SELECT DISTINCT 
					O.DATA_OCORRENCIA

					, (CASE 
						WHEN O.RESPONSAVEL = 'AUTOMATICO' THEN 'AUTOMATICO' 
						WHEN O.RESPONSAVEL IS NULL THEN 'AUTOMATICO' 
					 ELSE 'MANUAL' 
					 END) AS  ACOMPANHAMENTO 
					, O.CODIGO_OCOR
					, (CASE 
						 WHEN O.DESCRICAO_OCOR = 'ENTREGA REALIZADA NORMALMENTE' AND M.DT_ENTREGA IS NULL THEN 'SISTEMA'
						 WHEN YEAR(M.PREVISAO_ENTREGA) = 1900 THEN 'TABELA'
						 WHEN O.FALHA_CLIENTE = 'S' THEN 'CLIENTE' 
						 WHEN O.FALHA_OPERACIONAL = 'S' THEN 'OPERACINAL'
					 ELSE 'OPERACINAL' 
					 END) AS RESPONSABILIDADE
			  
					, O.DESCRICAO_OCOR

					, M.*	
					FROM 	tb_dados_movimento_custo_emis AS M	
						LEFT JOIN 	tb_solid_ocorrencias  AS O	
						ON 	concat(cast(M.NR_ENTRADA as char) , M.SIGLA_FIL) = concat(cast(O.NR_ENTRADA as CHAR), O.SIGLA_FIL)
					WHERE
						M.TIPO_DOC = 'CO'
						AND M.DT_EMISSAO >= '20200101' 	
							AND O.DATA_OCORRENCIA = 
								( SELECT 
									COALESCE(MAX(ODM.DATA_OCORRENCIA),
										(SELECT 
											MAX(ODM2.DATA_OCORRENCIA)	
										FROM tb_solid_ocorrencias AS ODM2
										WHERE
											ODM2. NR_ENTRADA = 	O. NR_ENTRADA
											AND	ODM2.SIGLA_FIL = O.SIGLA_FIL
										)
									) as DXM
								FROM tb_solid_ocorrencias AS ODM
								WHERE ODM. NR_ENTRADA = O. NR_ENTRADA
								AND	ODM.SIGLA_FIL =	O.SIGLA_FIL
								AND ODM.RESPONSAVEL != 'AUTOMATICO'
							   )
						and O.CODIGO_OCOR = 
						  ( SELECT 
								COALESCE(MIN(ODM.CODIGO_OCOR),
									(SELECT 
										MIN(ODM2.CODIGO_OCOR)	
									FROM tb_solid_ocorrencias AS ODM2
									WHERE
										ODM2. NR_ENTRADA = 	O. NR_ENTRADA
										AND	ODM2.SIGLA_FIL = O.SIGLA_FIL
										AND ODM2.DATA_OCORRENCIA = O.DATA_OCORRENCIA
									)
								) as DXM
							FROM tb_solid_ocorrencias AS ODM
							WHERE ODM. NR_ENTRADA = O. NR_ENTRADA
							AND	ODM.SIGLA_FIL =	O.SIGLA_FIL
							AND ODM.RESPONSAVEL != 'AUTOMATICO'
							AND ODM.DATA_OCORRENCIA = O.DATA_OCORRENCIA
						   )
	 
					UNION ALL

					SELECT  NULL,'NF DE SERVIÇO', 	NULL, 'NF DE SERVIÇO',NULL,  MNF.*
					FROM	tb_dados_movimento_custo_emis AS MNF 
					WHERE 
						TIPO_DOC = 'NF'	
						AND	MNF.DT_EMISSAO >= '20200101'
				) MONF 
				LEFT JOIN tb_solid_dados_cliente AS CL ON  MONF.CGC_CONSIG = CL.CGC
				where
				cl.DT_INCL_CLI = 
					(
						SELECT MAX(TBCL.DT_INCL_CLI) FROM tb_solid_dados_cliente AS TBCL
						WHERE TBCL.CGC = CL.CGC
					)
		) MONFCL
		LEFT JOIN (
			  select  distinct  cli.nr_cnpj_cpf , usu.nm_usuario
					from bd_portal_tsv.dbo.tb_usuario usu        
						inner join bd_portal_tsv.dbo.tb_usuario_cliente uCli on uCli.id_usuario = usu.cod_user
						inner join bd_fin_tsv.dbo.tb_cliente cli on cli.cod_cliente  = uCli.id_cliente      
						where usu.fl_status = 'A' and usu.funcao = 'ATENDENTE' and usu.ds_funcao = 'A'  and uCli.dt_cancela is null
				

				) AS SAC
			ON MONFCL.CGC_CONSIG = SAC.nr_cnpj_cpf
		LEFT JOIN 
			 tb_solid_nfs_ctes AS NFS
			ON 	concat(cast(MONFCL.NR_ENTRADA as char) , MONFCL.SIGLA_FIL) = concat(cast(NFS.NR_ENTRADA as CHAR), NFS.SIGLA_FIL)
		WHERE 
				MONFCL.DT_ENTREGA is  null

   ) AS MONFCLMNF
LEFT JOIN
	tb_dados_manifesto_custo_emis AS MNF
	ON 	concat(cast(MONFCLMNF.NR_ENTRADA as char) , MONFCLMNF.SIGLA_FIL) = concat(cast(MNF.NR_ENTRADA as CHAR), MNF.SIGLA_FIL)
	  WHERE
		 MNF.DT_EMISSAO_MANIFESTO = 
			(
				SELECT MAX(MNFDX.DT_EMISSAO_MANIFESTO) FROM tb_dados_manifesto_custo_emis AS MNFDX
				WHERE 
						MNFDX.NR_ENTRADA = 	MNF.NR_ENTRADA
					AND	MNFDX.SIGLA_FIL = MNF.SIGLA_FIL
			)
		OR 
		 MNF.DT_EMISSAO_MANIFESTO IS NULL