SELECT  *
FROM tb_dados_movimento_custo_emis AS M	
WHERE
M.TIPO_DOC in ('CO','NF')
 AND M.DT_EMISSAO >= '20200401'
 AND M.DT_ENTREGA is  null
 AND M.DESCR_TIPO_TRANSP  IN('RODO','SUBCONTRATACAO','ICMS SUBCONT')