SELECT DISTINCT 
O.DATA_OCORRENCIA, 
(CASE WHEN O.RESPONSAVEL = 'AUTOMATICO'  THEN 'AUTOMATICAS' WHEN O.RESPONSAVEL IS NULL THEN 'AUTOMATICAS' ELSE 'MANUAIS' END) AS  TIPO_OCORRENCIA 
, O.CODIGO_OCOR, (CASE WHEN O.FALHA_CLIENTE = 'S' THEN 'CLIENTE' 
ELSE 
(CASE WHEN O.FALHA_OPERACIONAL = 'S' THEN 'TSV' ELSE 'INDEFINIDO' END) 	
END) AS RESPONSABILIDADE
,COALESCE(O.RESPONSAVEL,'AUTOMATICO') AS SAC 
, O.DESCRICAO_OCOR
, O.CODIGO_OCOR
, O.DT_ATUALIZADO
,O.DT_LANCAMENTO
, M.NUM_DOC
,M.SERIE_DOC
,M.SIGLA_FIL
,M.COD_DADOS_MOVIMENTO_CUSTO_EMIS
FROM 	tb_solid_ocorrencias AS O 	
LEFT JOIN 	tb_dados_movimento_custo_emis AS M	
ON 	 concat(cast(O.NR_ENTRADA as CHAR), O.SIGLA_FIL) =concat(cast(M.NR_ENTRADA as char) , M.SIGLA_FIL) 
WHERE
M.TIPO_DOC = 'CO'
AND M.DT_ENTREGA IS NULL
AND M.DT_EMISSAO >= '20180101'
