/*
tb_dados_rom_coleta_custo_emis

*/

select DISTINCT
	 VCC.DESCR_TIPO_PAGTO
	,TIPO_CONTRATO
	,VCC.DEB_CRED_TIPO_PAGTO
	,VCC.DT_EMIS_CONTRATO
	,vcc.DATA_PAGAMENTO
	,Frete_Cte.DT_EMISS_ROM_COL
	,VCC.FIL_CONTRATO
	,VCC.NUM_CONTRATO
	,VCC.PLACA_PRINCIPAL
	,VCC.VALOR_CONTRATO
	,(Frete_Cte.NUM_DOCs/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO)AS NUM_DOCs_RATEIO
	,(Frete_Cte.FRETE/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO) AS FRETE_RATEIO 
	,(Frete_Cte.PESO_MOV/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO) /1000 AS PESO_MOV_RATEIO_TON 

	,Frete_Cte.FRETE
	,QTD_DEB_CRED_TIPO_PAGTO
	FROM
		(
			select DISTINCT DMCE.DT_EMISS_ROM_COL,  dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,count(DMCE.NUM_DOC) as NUM_DOCs, sum(DRECE.frete) as FRETE, SUM(DRECE.PESO_MOV)/100 AS PESO_MOV 
			from tb_dados_rom_coleta_custo_emis  as DMCE
			right  JOIN
			tb_dados_movimento_custo_emis DRECE
			ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
			WHERE DRECE.TIPO_DOC IN ('CO','NF') AND DRECE.nr_peso_rel IS NOT NULL
			group by 
			 dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,DMCE.DT_EMISS_ROM_COL
		) 
		AS Frete_Cte
		inner JOIN
		(
			SELECT DISTINCT TIPO_CONTRATO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, DATA_PAGAMENTO ,COUNT( DESCR_TIPO_PAGTO) QTD_DEB_CRED_TIPO_PAGTO 
			FROM  Tb_valores_contrato_custo
			WHERE DESCR_TIPO_PAGTO != 'TOTALBRUTO' and  DEB_CRED_TIPO_PAGTO = 'C' 
			group by TIPO_CONTRATO,  DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO,DATA_PAGAMENTO
		) AS VCC_cont
		ON Frete_Cte.NUM_CONTRATO  = VCC_cont.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC_cont.FIL_CONTRATO AND CAST(Frete_Cte.DT_EMISS_ROM_COL AS DATE) = CAST(VCC_cont.DATA_PAGAMENTO AS DATE)
		 inner JOIN
		(
			SELECT DISTINCT DESCR_TIPO_PAGTO, DEB_CRED_TIPO_PAGTO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, DATA_PAGAMENTO , sum(VALOR_CONTRATO) as VALOR_CONTRATO
			FROM  Tb_valores_contrato_custo
			WHERE DESCR_TIPO_PAGTO != 'TOTALBRUTO' and  DEB_CRED_TIPO_PAGTO = 'C' group by DESCR_TIPO_PAGTO, DEB_CRED_TIPO_PAGTO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO,DATA_PAGAMENTO
		) 
		AS VCC
		ON Frete_Cte.NUM_CONTRATO  = VCC.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC.FIL_CONTRATO AND CAST(Frete_Cte.DT_EMISS_ROM_COL AS DATE) = CAST(VCC.DATA_PAGAMENTO AS DATE)
		WHERE VCC.DT_EMIS_CONTRATO between '20200501' and '20200531'
		and VCC.FIL_CONTRATO = 'RIO'




/*tb_dados_rom_entrega_custo_em*/

select DISTINCT
	 VCC.DESCR_TIPO_PAGTO
	,TIPO_CONTRATO
	,VCC.DEB_CRED_TIPO_PAGTO
	,VCC.DT_EMIS_CONTRATO
	,vcc.DATA_PAGAMENTO
	,Frete_Cte.DT_EMISS_ROM_ENT
	,VCC.FIL_CONTRATO
	,VCC.NUM_CONTRATO
	,VCC.PLACA_PRINCIPAL
	,VCC.VALOR_CONTRATO
	,(Frete_Cte.NUM_DOCs/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO)AS NUM_DOCs_RATEIO
	,(Frete_Cte.FRETE/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO) AS FRETE_RATEIO 
	,(Frete_Cte.PESO_MOV/VCC_cont.QTD_DEB_CRED_TIPO_PAGTO) /1000 AS PESO_MOV_RATEIO_TON 

	,Frete_Cte.FRETE
	,QTD_DEB_CRED_TIPO_PAGTO
	FROM
		(
			select DISTINCT  DMCE.DT_EMISS_ROM_ENT,  dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,count(DMCE.NUM_DOC) as NUM_DOCs, sum(DRECE.frete) as FRETE, SUM(DRECE.PESO_MOV)/100 AS PESO_MOV 
			from tb_dados_rom_entrega_custo_em  as DMCE
			right  JOIN
			tb_dados_movimento_custo_emis DRECE
			ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
			WHERE DRECE.TIPO_DOC IN ('CO','NF') AND DRECE.nr_peso_rel IS NOT NULL
			group by 
			 dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,DMCE.DT_EMISS_ROM_ENT
		) 
		AS Frete_Cte
		inner JOIN
		(
			SELECT DISTINCT TIPO_CONTRATO,  DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, DATA_PAGAMENTO ,COUNT( DESCR_TIPO_PAGTO) QTD_DEB_CRED_TIPO_PAGTO 
			FROM  Tb_valores_contrato_custo
			WHERE DESCR_TIPO_PAGTO != 'TOTALBRUTO' and  DEB_CRED_TIPO_PAGTO = 'C' 
			group by TIPO_CONTRATO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO,DATA_PAGAMENTO
		) AS VCC_cont
		ON Frete_Cte.NUM_CONTRATO  = VCC_cont.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC_cont.FIL_CONTRATO AND CAST(Frete_Cte.DT_EMISS_ROM_ENT AS DATE) = CAST(VCC_cont.DATA_PAGAMENTO AS DATE)
		 inner JOIN
		(
			SELECT DISTINCT DESCR_TIPO_PAGTO, DEB_CRED_TIPO_PAGTO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, DATA_PAGAMENTO , sum(VALOR_CONTRATO) as VALOR_CONTRATO
			FROM  Tb_valores_contrato_custo
			WHERE DESCR_TIPO_PAGTO != 'TOTALBRUTO' and  DEB_CRED_TIPO_PAGTO = 'C' group by DESCR_TIPO_PAGTO, DEB_CRED_TIPO_PAGTO, DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO,DATA_PAGAMENTO
		) 
		AS VCC
		ON Frete_Cte.NUM_CONTRATO  = VCC.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC.FIL_CONTRATO AND CAST(Frete_Cte.DT_EMISS_ROM_ENT AS DATE) = CAST(VCC.DATA_PAGAMENTO AS DATE)
		WHERE VCC.DT_EMIS_CONTRATO between '20200501' and '20200531'
		and VCC.FIL_CONTRATO = 'RIO'

		SELECT VAL_MERC_MOV FROM tb_dados_movimento_custo_emis