

	select Frete_Cte.DT_EMISS_ROM_ENT, Frete_Cte.NRO_ROMANEIO_ENTREGA, VCC.DT_EMIS_CONTRATO, VCC.FIL_CONTRATO,VCC.NUM_CONTRATO,VCC.PLACA_PRINCIPAL,VCC.VALOR_CONTRATO,Frete_Cte.NUM_DOCs,Frete_Cte.FRETE  from
		(
			select dmce.DT_EMISS_ROM_ENT, dmce.NRO_ROMANEIO_ENTREGA,  dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,count(DMCE.NUM_DOC) as NUM_DOCs, sum(DRECE.frete) as FRETE from tb_dados_rom_entrega_custo_em  as DMCE
			left  JOIN
			tb_dados_movimento_custo_emis DRECE
			ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
			group by 
			dmce.NRO_ROMANEIO_ENTREGA, DMCE.DT_EMISS_ROM_ENT, dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO 
		) as Frete_Cte
		right JOIN
		(SELECT DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, sum(VALOR_CONTRATO) as VALOR_CONTRATO FROM  Tb_valores_contrato_custo WHERE DEB_CRED_TIPO_PAGTO = 'C' and DESCR_TIPO_PAGTO != 'TOTALBRUTO'  group by DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO) AS VCC
		ON Frete_Cte.NUM_CONTRATO  = VCC.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC.FIL_CONTRATO
		WHERE VCC.DT_EMIS_CONTRATO between '20200501' and '20200531'
		and VCC.FIL_CONTRATO = 'RIO'
		

		/*testes*/

			select Frete_Cte.DT_EMISS_ROM_ENT, Frete_Cte.NRO_ROMANEIO_ENTREGA,Frete_Cte.NUM_DOCs,Frete_Cte.FRETE  from
		(
			select DISTINCT DMCE.DT_EMISS_ROM_ENT, dmce.NRO_ROMANEIO_ENTREGA,  dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,count(DMCE.NUM_DOC) as NUM_DOCs, sum(DRECE.frete) as FRETE from tb_dados_rom_entrega_custo_em  as DMCE
			left  JOIN
			tb_dados_movimento_custo_emis DRECE
			ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
			group by 
			dmce.NRO_ROMANEIO_ENTREGA, DMCE.DT_EMISS_ROM_ENT, dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO 
		) as Frete_Cte
		where Frete_Cte.DT_EMISS_ROM_ENT > '20200701'
		order by NRO_ROMANEIO_ENTREGA


		/*            */
		select DISTINCT  VCC.DT_EMIS_CONTRATO, VCC.FIL_CONTRATO,VCC.NUM_CONTRATO,VCC.PLACA_PRINCIPAL, VCC.VALOR_CONTRATO, Frete_Cte.NUM_DOCs,Frete_Cte.FRETE  from
		(
			select DISTINCT  dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO ,count(DMCE.NUM_DOC) as NUM_DOCs, sum(DRECE.frete) as FRETE from tb_dados_rom_entrega_custo_em  as DMCE
			left  JOIN
			tb_dados_movimento_custo_emis DRECE
			ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
			group by 
			 dmce.NUM_CONTRATO, DMCE.FIL_CONTRATO 
		) as Frete_Cte
		 JOIN
		(SELECT DISTINCT DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, sum(VALOR_CONTRATO) as VALOR_CONTRATO FROM  Tb_valores_contrato_custo WHERE DESCR_TIPO_PAGTO = 'PROD. ENTREGA'  group by DT_EMIS_CONTRATO, PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO) AS VCC
		ON Frete_Cte.NUM_CONTRATO  = VCC.NUM_CONTRATO AND Frete_Cte.FIL_CONTRATO = VCC.FIL_CONTRATO
		WHERE VCC.DT_EMIS_CONTRATO between '20200501' and '20200531'
		and VCC.FIL_CONTRATO = 'RIO'

	