SELECT DISTINCT  DMC02.SIGLA_FIL, DMC02.NR_ENTRADA, DMC02.NUM_DOC, DRECE3.DT_EMISS_ROM_ENT ,  VCC.PLACA_PRINCIPAL, VCC.NOME_MOT , vcc.FIL_CONTRATO, DMC02.PREVISAO_ENTREGA, dbo.fn_ret_notas_cte(DMC02.NR_ENTRADA, DMC02.SIGLA_FIL) AS NOTA_AGRUP,FRETE, cont_cliente ,cont_Operacional  FROM   tb_dados_movimento_custo_emis  AS DMC02  with(nolock) 
							INNER JOIN 
								(SELECT DISTINCT SO01.NR_ENTRADA, SO01.SIGLA_FIL, count(case when SO01.FALHA_CLIENTE = 'S' then 1 else null end) as cont_cliente, count(case when SO01.FALHA_OPERACIONAL = 'S' then 1 else null end) as cont_Operacional     FROM tb_solid_ocorrencias AS SO01  with(nolock)
														group by  SO01.NR_ENTRADA, SO01.SIGLA_FIL
														
								) AS SO03 
							ON DMC02.NR_ENTRADA = SO03.NR_ENTRADA AND DMC02.SIGLA_FIL = SO03.SIGLA_FIL
	
						INNER JOIN
							( SELECT DISTINCT DRECE2.NR_ENTRADA,DRECE2.SIGLA_FIL, NUM_CONTRATO, FIL_CONTRATO , DT_EMISS_ROM_ENT FROM tb_dados_rom_entrega_custo_em DRECE2  with(nolock) ) AS DRECE3
							ON DMC02.NR_ENTRADA = DRECE3.NR_ENTRADA AND DMC02.SIGLA_FIL = DRECE3.SIGLA_FIL
						LEFT JOIN
							(SELECT DISTINCT  PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO , NOME_MOT ,VALOR_CONTRATO  FROM Tb_valores_contrato_custo  with(nolock)) AS VCC
							ON DRECE3.NUM_CONTRATO  = VCC.NUM_CONTRATO AND DRECE3.FIL_CONTRATO = VCC.FIL_CONTRATO
							WHERE
							DMC02.NUM_DOC = 424314
							and VCC.FIL_CONTRATO = 'BSB'
					
				 