 SELECT DISTINCT
	TABELA.* 
	,ISNULL(PRAZO.PRAZO_PARCEIRO,3) AS PRAZO_PARCEIRO
	,(CASE 	
		WHEN TABELA.DIAS_ATRASO  <= 0 THEN 'NO_PRAZO'
		WHEN isnull(TABELA.FALHA_CLIENTE,'') = 'S'  THEN 'CLIENTE' 	
		WHEN TABELA.TIPO_ENTREGA = 'DISTRIBUIÇÃO'  THEN 'DISTRIBUIÇÃO'
		WHEN Dias_Redespacho > ISNULL(PRAZO.PRAZO_PARCEIRO,3) then 'REDESPACHO'  else 'DISTRIBUIÇÃO'
		END) AS Responsavel
	,(CASE 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  1 AND 3 THEN '1 A 3' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  4 AND 6 THEN '4 A 6' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  7 AND 14 THEN '7 A 14' 
		WHEN TABELA.DIAS_ATRASO BETWEEN  15 AND 30 THEN '15 A 30' 
		WHEN TABELA.DIAS_ATRASO >30 THEN ' > 30' 
		WHEN TABELA.DIAS_ATRASO = 0 THEN 'Na_Data'
		WHEN TABELA.DIAS_ATRASO BETWEEN  -3 AND -1 THEN '1 A 3.' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN -6 AND -4 THEN '4 A 6.' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  -14 AND -5 THEN '7 A 14.' 
		WHEN TABELA.DIAS_ATRASO BETWEEN  -30 AND -15 THEN '15 A 30.' 
		WHEN TABELA.DIAS_ATRASO < -30 THEN ' > 30.'
		ELSE 'NO PRAZO' 
		END) AS FAIXA_ATRASO 
	
	,(CASE 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  1 AND 3 THEN '1 A 3' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  4 AND 6 THEN '4 A 6' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  7 AND 14 THEN '7 A 14' 
		WHEN TABELA.DIAS_ATRASO BETWEEN  15 AND 30 THEN '15 A 30' 
		WHEN TABELA.DIAS_ATRASO >30 THEN ' > 30' 
		ELSE 'NO PRAZO' 
		END) AS FAIXA_ATRASO_2
	,(CASE             
		WHEN TABELA.DIAS_ATRASO  <= 0 THEN 'NO_PRAZO'  ELSE 'ATRASADO'  
		END) AS STATUS_ENTREGA
	 ,(CASE
		WHEN TABELA.DIAS_ATRASO  > 0 THEN TABELA.NUM_DOC 
		END) AS DOC_ATRASADO
	 , GETDATE() AS ATUALIZACAO_PAINEL
	,(CASE
		WHEN TABELA.DIAS_ATRASO  <= 0 THEN 'NO_PRAZO' 
		WHEN isnull(TABELA.FALHA_CLIENTE,'') = 'S' AND TABELA.DIAS_ATRASO >0  THEN 'CLIENTE' 			
		ELSE 'OPERACIONAL' 	
	END) AS RESPONSABILIDADE
	,(CASE 
				WHEN TABELA.Filial_Faturamento IN('ACR','BhZ','CPQ','ITA','RDN','SPO','UDI','PPY','EXT') THEN 'SPO'
				WHEN TABELA.SIGLA_FIL_DEST IN('BNU','ITJ','FLN') THEN 'BNU'
				ELSE TABELA.Filial_Faturamento 
			END ) AS Filial_Faturamento_GROUP
	,upper(FORMAT(TABELA.PREVISAO_ENTREGA,'MMMM','pt-BR')) as MeS_PREVISAO_ENTREGA
	,right(replicate('0',2) + convert(VARCHAR,MONTH(TABELA.PREVISAO_ENTREGA)),2) +'_'+ upper(FORMAT(TABELA.PREVISAO_ENTREGA,'MMMM','pt-BR')) as MeS_PREVISAO_ENTREGA_FILTRO
	FROM	
			(SELECT DISTINCT 

			DMC02.SIGLA_FIL
			,CONCAT( DMC02.SIGLA_FIL,' ', cast(DMC02.NUM_DOC as char)) AS NUM_DOC
			,DMC02.NR_COLETA
			,DMC02.DATA_COLETA
			,DMC02.DT_EMISSAO
			,DMC02.DT_ENTREGA
			,DMC02.CGC_REMET
			,DMC02.REMETENTE
			,DMC02.CGC_DEST
			,DMC02.DESTINATARIO
			,DMC02.CGC_CONSIG
			,DMC02.CONSIGNATARIO
			,DMC02.LOCAL_ENTREGA
			,DMC02.CIDADE_DESTINO
			,DMC02.ESTADO_DESTINO
			,DMC02.RT1
			,DMC02.RT2
			,DMC02.RT3
			,(CASE
			WHEN DMC02.TIPO_FRETE = 'F' THEN DMC02.RT3 ELSE DMC02.RT1
			END) AS Filial_Faturamento
			,(CASE 	
			WHEN DMC02.DESCR_TIPO_TRANSP = 'REENTREGA' THEN 'REENTREGA'
			WHEN DMC02.DESCR_TIPO_TRANSP = 'COMPLEMENTAR' OR DMC02.FRETE < 35 THEN 'COMPLEMENTAR'
			WHEN DMC02.nr_peso_cub_pad BETWEEN  0 AND 10    THEN '0.000 A 0.010 T' 	
			WHEN DMC02.nr_peso_cub_pad BETWEEN  10 AND 20   THEN '0.011 A 0.020 T' 	
			WHEN DMC02.nr_peso_cub_pad BETWEEN  20 AND 30   THEN '0.021 A 0.030 T'  
			WHEN DMC02.nr_peso_cub_pad BETWEEN  30 AND 50   THEN '0.031 A 0.050 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  50 AND 70   THEN '0.051 A 0.070 T' 	
			WHEN DMC02.nr_peso_cub_pad BETWEEN  70 AND 100  THEN '0.071 A 0.100 T' 	
			WHEN DMC02.nr_peso_cub_pad BETWEEN  100 AND 150  THEN '0.101 A 0.150 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  150 AND 200 THEN '0.151 A 0.200 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  200 AND 1000 THEN '0.201 A 1.000 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  1000 AND 4000 THEN '1.000 A 4.000 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  4000 AND 10000 THEN '4.000 A 10.000 T' 
			WHEN DMC02.nr_peso_cub_pad BETWEEN  10000 AND 14999 THEN '10.001 A 15.000 T' 
			WHEN DMC02.nr_peso_cub_pad >= 15000 THEN 'LOTATAÇÃO >15 T' 
			END) AS FAIXA_nr_peso_cub_pad 
			,(CASE 	
			WHEN DMC02.DESCR_TIPO_TRANSP = 'REENTREGA' THEN 'REENTREGA'
			WHEN DMC02.DESCR_TIPO_TRANSP = 'COMPLEMENTAR' OR DMC02.FRETE < 35 THEN 'COMPLEMENTAR'
			WHEN DMC02.PESO_CUBADO BETWEEN  0 AND 10    THEN '0.000 A 0.010 T' 	
			WHEN DMC02.PESO_CUBADO BETWEEN  10 AND 20   THEN '0.011 A 0.020 T' 	
			WHEN DMC02.PESO_CUBADO BETWEEN  20 AND 30   THEN '0.021 A 0.030 T'  
			WHEN DMC02.PESO_CUBADO BETWEEN  30 AND 50   THEN '0.031 A 0.050 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  50 AND 70   THEN '0.051 A 0.070 T' 	
			WHEN DMC02.PESO_CUBADO BETWEEN  70 AND 100  THEN '0.071 A 0.100 T' 	
			WHEN DMC02.PESO_CUBADO BETWEEN  100 AND 150  THEN '0.101 A 0.150 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  150 AND 200 THEN '0.151 A 0.200 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  200 AND 1000 THEN '0.201 A 1.000 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  1000 AND 4000 THEN '1.000 A 4.000 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  4000 AND 10000 THEN '4.000 A 10.000 T' 
			WHEN DMC02.PESO_CUBADO BETWEEN  10000 AND 14999 THEN '10.001 A 15.000 T' 
			WHEN DMC02.PESO_CUBADO >= 15000 THEN 'LOTATAÇÃO >15 T' 
			END) AS FAIXA_PESO_CUBADO
			,(CASE 	
			WHEN DMC02.DESCR_TIPO_TRANSP = 'REENTREGA' THEN 'REENTREGA'
			WHEN DMC02.DESCR_TIPO_TRANSP = 'COMPLEMENTAR' OR DMC02.FRETE < 35 THEN 'COMPLEMENTAR'
			WHEN DMC02.nr_peso_rel BETWEEN  0 AND 10    THEN '0.000 A 0.010 T' 	
			WHEN DMC02.nr_peso_rel BETWEEN  10 AND 20   THEN '0.011 A 0.020 T' 	
			WHEN DMC02.nr_peso_rel BETWEEN  20 AND 30   THEN '0.021 A 0.030 T'  
			WHEN DMC02.nr_peso_rel BETWEEN  30 AND 50   THEN '0.031 A 0.050 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  50 AND 70   THEN '0.051 A 0.070 T' 	
			WHEN DMC02.nr_peso_rel BETWEEN  70 AND 100  THEN '0.071 A 0.100 T' 	
			WHEN DMC02.nr_peso_rel BETWEEN  100 AND 150  THEN '0.101 A 0.150 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  150 AND 200 THEN '0.151 A 0.200 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  200 AND 1000 THEN '0.201 A 1.000 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  1000 AND 4000 THEN '1.000 A 4.000 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  4000 AND 10000 THEN '4.000 A 10.000 T' 
			WHEN DMC02.nr_peso_rel BETWEEN  10000 AND 14999 THEN '10.001 A 15.000 T' 
			WHEN DMC02.nr_peso_rel >= 15000 THEN 'LOTATAÇÃO >15 T' 
			END) AS FAIXA_nr_peso_rel
			,(DATEDIFF(dd,RomRed.DT_EMISS_ROM_RED, isnull(DMC02.DT_ENTREGA,GETDATE())))
				-(DATEDIFF(wk, RomRed.DT_EMISS_ROM_RED, isnull(DMC02.DT_ENTREGA,GETDATE())) * 2)
				-(CASE WHEN DATEPART(dw, isnull(DMC02.DT_ENTREGA,GETDATE())) = 1 THEN 1 ELSE 0 END)
				-(CASE WHEN DATEPART(dw, isnull(DMC02.DT_ENTREGA,GETDATE())) = 7 THEN 1 ELSE 0 END) 
			as Dias_Redespacho
			,(CASE 
				WHEN DMC02.RT4 = 'I' THEN 'INTERIOR' 
				WHEN DMC02.RT4 = 'C' THEN 'CAPITAL' 	
				ELSE 'INTERIOR 02' 	
				END) AS RT4
			,(CASE 			
				WHEN DMC02.ESTADO_DESTINO IN ('DF','GO','MS','MT') THEN 'Centro-Oeste'
				WHEN DMC02.ESTADO_DESTINO IN ('AL','BA','CE','MA','PB','PE','PI','RN','SE') THEN 'Nordeste' 
				WHEN DMC02.ESTADO_DESTINO IN ('AC','AM','AP','PA','RO','RR','TO') THEN 'Norte' 
				WHEN DMC02.ESTADO_DESTINO IN ('ES','MG','RJ','SP') THEN 'Sudeste' 	
				WHEN DMC02.ESTADO_DESTINO IN ('PR','RS','SC') THEN 'Sul' 		
				END) AS REGIAO_DESTINO
			,(CASE 			
				WHEN DMC02.ESTADO IN ('DF','GO','MS','MT') THEN 'Centro-Oeste'
				WHEN DMC02.ESTADO IN ('AL','BA','CE','MA','PB','PE','PI','RN','SE') THEN 'Nordeste' 
				WHEN DMC02.ESTADO IN ('AC','AM','AP','PA','RO','RR','TO') THEN 'Norte' 
				WHEN DMC02.ESTADO IN ('ES','MG','RJ','SP') THEN 'Sudeste' 	
				WHEN DMC02.ESTADO IN ('PR','RS','SC') THEN 'Sul' 		
				END) AS REGIAO_ORIGEM
			,DMC02.CIDADE
			,DMC02.ESTADO
			,DMC02.CEP_DEST
			,(CASE 	
				WHEN SDC03.DESCR_GRUPO_CLIENTE = '' THEN DMC02.CONSIGNATARIO 	
				WHEN SDC03.DESCR_GRUPO_CLIENTE IS NULL THEN DMC02.CONSIGNATARIO 
				ELSE SDC03.DESCR_GRUPO_CLIENTE  
				END) AS CLIENTE_GRUPO
			,(CASE 		
				WHEN VRCE.RAZAO IS NOT NULL THEN 'REDESPACHO' 
				ELSE 'DISTRIBUIÇÃO' END) AS TIPO_ENTREGA
			,(CASE 		
				WHEN VRCE.RAZAO IS NOT NULL THEN VRCE.RAZAO
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL THEN VCC.PLACA_PRINCIPAL
				WHEN DMFCE03.NRO_MANIFESTO IS NULL THEN DMC02.SIGLA_FIL
				WHEN DMFCE03.DT_CHEGADA IS NULL THEN  substring(DMFCE03.NRO_MANIFESTO,5,3)
				WHEN (DMFCE03.FIL_BAIXA_MNF = DMC02.RT3) THEN DMC02.RT3
				WHEN (DMFCE03.FIL_BAIXA_MNF <> DMC02.RT3) THEN  substring(DMFCE03.NRO_MANIFESTO,5,3)
				ELSE '-' END) AS NOME_PROP
			,(CASE 		
				WHEN (DMFCE03.FIL_BAIXA_MNF = DMC02.SIGLA_FIL_DEST) THEN DMFCE03.DT_BAIXA
				ELSE null END) AS DT_Baixa_Dest
			,DATEDIFF(DD,DMC02.DATA_COLETA,DMC02.DT_EMISSAO) AS DIAS_CLT_EMS
			,(CASE 
				WHEN DMC02.DESTINATARIO IN 
							(
							'RAIA DROGASIL S A',
							'RAIA DROGASIL S.A',
							'RAIA DROGASIL S.A.',
							'RAIA DROGASIL S/A',
							'RAIA DROGASIL S/A - LOJA 712 CAMPO GRANDE AFONSO P',
							'RAIA DROGASIL S/A - LOJA 713 CAMPO GRANDE 13 DE JU',
							'RAIA DROGASIL S/A - LOJA 714',
							'RAIA DROGASIL S/A - LOJA 723 DOURADOS',
							'RAIA DROGASIL S/A - LOJA 739 - SHOPPING CAMPO GRAN',
							'RAIA DROGASIL S/A- 1019R EUSTAQUIO B (PE EUSTAQUIO',
							'RAIA DROGASIL S/A-1326D - GO JD NOVO MUNDO',
							'RAIA DROGASIL SA',
							'RAIA DROGASIL/SA.',
							'DROGARIA PACHECO S.A.',
							'DROGARIA PACHECO SA',
							'PANPHARMA DIST DE MEDICAMENTO LTDA',
							'PANPHARMA DIST DE MEDICAMENTOS LTDA',
							'PANPHARMA DISTRIB DE MEDICAMENTOS LTDA',
							'PANPHARMA DISTRIBUIDOR,A DE MEDICAMENTOS, LTDA',
							'PANPHARMA DIT DE MEDICAMENTOS LTDA',
							'SENDAS DIST. S A',
							'SENDAS DISTRIBUIDORA',
							'SENDAS DISTRIBUIDORA S A',
							'SENDAS DISTRIBUIDORA S.A',
							'SENDAS DISTRIBUIDORA S.A.',
							'SENDAS DISTRIBUIDORA S/A',
							'SENDAS DISTRIBUIDORA SA',
							'SENDAS DISTRIBUIDORA SA LOJA 102',
							'SENDAS DISTRIBUIDORA SA LOJA 57',
							'SENDAS DISTRIBUIDORA SA LOJA 70',
							'DISTR. DE MED STA CRUZ LTDA',
							'SDB COM DE ALIMENTOS LTDA',
							'SDB COMERCIO DE ALIMENTOS LTDA',
							'SDB COMERCIO DE ALIMENTOS LTDA (FORT AREAO - MT)',
							'SDB COMERCIO DE ALM LTDA (FORT TAGUATINGA - DF)',
							'SDB METERIG SISTEMAS DE MEDICAO LTDA',
							'DIST MEDICAMENTOS STA CRUZ LTDA',
							'DISPAR DISTRIBUIDORA DE MEDICAMENTOS LTDA',
							'VENANCIO PRODS FARMAC LTDA',
							'VENANCIO PRODUTOS FARMACEUTICOS LTDA',
							'VENANCIO PRODUTOS FARMACEUTICOS LTD',
							'VENANCIO PRODUTOS FARMACEUTICOS LTDA',
							'CARREFOUR COM IND LTDA',
							'CARREFOUR COM INDUSTRIA LTDA',
							'CARREFOUR COMERCIO E INDUSTRIA LTDA',
							'ATACADAO S A 47791',
							'ATACADAO BARATAO LTDA',
							'ATACADAO COMERCIO DE GENEROS ALIMENTICIOS LTDA',
							'ATACADAO COMERCIO DE PECAS AGRICOLAS',
							'ATACADAO DA CONSTRUCAO LTDA',
							'ATACADAO DA PROTEÇÃO IND E COMERCIO EQUIPAMENTOS',
							'ATACADAO DA RACAO COMERCIO DE PRODUTOS AGROPECUARI',
							'ATACADAO DAS BATERIAS LTDA',
							'ATACADAO DAS EMBALAGENS EIRELI',
							'ATACADAO DIST COM E IND LTDA',
							'ATACADAO DIST COM E INDUSTRIA LTDA',
							'ATACADAO DIST COM IND LTDA',
							'ATACADAO DIST COMERCIO E INDUSTRIA LTDA',
							'ATACADAO DISTB LTDA',
							'ATACADAO DISTR COM E IND LTDA',
							'ATACADAO DISTR COM IND LTDA',
							'ATACADAO DISTR COM IND. LTDA 30',
							'ATACADAO DISTR.COM. E IND. LTDA',
							'ATACADAO DISTR.COMERCIO E INDUSTRIA LTDA',
							'ATACADAO DISTRIB COM E IND LTDA',
							'ATACADAO DISTRIBUICAO COM E IND LTDA',
							'ATACADAO DISTRIBUICAO COM IND LTDA',
							'ATACADAO DISTRIBUICAO COM LTDA',
							'ATACADAO DISTRIBUICAO COMERCIO E IND LTDA',
							'ATACADAO DISTRIBUICAO COMERCIO E INDUSTRIA LTDA',
							'ATACADAO DISTRIBUIDORA COMERCIO E IND LTDA',
							'ATACADAO DISTRUICAO COM INDUSTRIA LTDA',
							'ATACADAO DO BEBE IND E COM DE CONF EIRELI',
							'ATACADAO DO RECUPERADOR (MARCOS P. M. DE SOUZA ME)',
							'ATACADAO MOTO PECAS LTDA',
							'ATACADAO MOTO PECAS LTDA - ME',
							'ATACADAO MOTO PEÇAS LTDA EPP',
							'ATACADAO PAPELEX LTDA',
							'ATACADAO S A',
							'ATACADAO S A 1525',
							'ATACADAO S A 36179',
							'ATACADAO S A 36188',
							'ATACADAO S A 37613',
							'ATACADAO S A 43025',
							'ATACADAO S A 63168',
							'ATACADAO S A 9684',
							'ATACADAO S A 9686',
							'ATACADAO S.A',
							'ATACADAO S.A 70650',
							'ATACADAO S.A.',
							'ATACADAO S/ A LJ202 - RJ',
							'ATACADAO S/A',
							'ATACADAO S/A.(LJ.174)',
							'ATACADAO S/A.(LJ.193)',
							'ATACADAO SA',
							'EMPREEMDIMENTOS PAGUE MENOS SA',
							'EMPREENDIMENTOS PAGUE MENOS',
							'EMPREENDIMENTOS PAGUE MENOS S A',
							'EMPREENDIMENTOS PAGUE MENOS S.A',
							'EMPREENDIMENTOS PAGUE MENOS S/A',
							'EMPREENDIMENTOS PAGUE MENOS SA',
							'PAGUE MENOS COM DE PROD ALIM LTDA *',
							'DROGARIA SAO PAULO S.A',
							'DROGARIA SAO PAULO S.A.',
							'DROGARIA SAO PAULO S/A',
							'DROGARIA SAO PAULO SA',
							'B2M ACATAREJO DO BRASIL LTDA',
							'B2M ATACAREJO DO BRASIL LTDA',
							'B2M ATACAREJOS DO BRASIL LTDA',
							'FARMACIA E DROGARIA NISSEI LTDA',
							'FARMACIA E DROGARIA NISSEI S A',
							'FARMACIA E DROGARIA NISSEI S/A',
							'DIMED S A DISTRIBUIDORA DE MEDICAM',
							'DIMED A DISTRIBUIDORA DE MEDICAM',
							'DIMED COM PREST SERVS LTDA',
							'DIMED S A DISTRIBUIDORA DE MEDICAM',
							'DIMED S/A DISTRIBUIDORA DE MEDICA',
							'DIMED SA DISTRIB DE MEDICAMENTOS',
							'DIMED SA DISTRIBUIDORA DE MEDICAMENTOS',
							'INTITUTO DE MEDICINA DIGITAL DIMEDI LTD',
							'CENTRO OESTE COM DE ALIM LTDA',
							'CENTRO OESTE COM LUBRIFICANTES LTDA',
							'CENTRO OESTE COMERCIAL DE ALIMENTOS LTDA',
							'CENTRO OESTE COM.ATAC.E VAREJ.DE COSEM.',
							'CENTRO OESTE COML DE ALIMENTOS EIRELI',
							'CENTRO OESTE COML DE ALIMENTOS LTDA',
							'PROFARMA DIST DE PRODS FARM SA',
							'PROFARMA DIST PRODS FARMACEUTICOS S A',
							'PROFARMA DISTR DE PRODS FARM S/A',
							'PROFARMA DISTR DE PRODS FARM SA',
							'PROFARMA DISTRIB DE PROD FARM SA',
							'PROFARMA DISTRIB DE PROD FARMAC S/A',
							'DEL MORO & DEL MORO',
							'DEL MORO & DEL MORO LTDA',
							'DEL MORO AMP AMP DEL MORO LTDA',
							'DEL MORO DEL MORO LTDA',
							'DEL MORO E DEL MORO LTDA',
							'GAZIN ATACADO CENTRO-OESTE LTDA',
							'GAZIN IND E COM DE MOVEIS E ELETROD LTDA',
							'GAZIN INFORMATICA LTDA',
							'CIA BRASILEIRA DE DISTRIBUICAO',
							'COMPANHIA BRASILEIRA DE DISTRIBUICA',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO 1018',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO1418',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO1635',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO1813',
							'COMPANHIA BRASILEIRA DE DISTRIBUICAO5267',
							'COMPANHIA BRASILEIRA DE DISTRIBUIÇÃ',
							'COMPANIA BRASILEIRA DE DISTRIBUIÇÃO',
							'EMPRESA BRASILEIRA DE DISTB LTDA',
							'STO ATACADISTA DE ALIMENTOS EIRELI',
							'PEROLA DISTRIBUICAO E LOGISTICA LTDA',
							'A B V COM DE ALIM LTDA',
							'SANGALETTI SANGALETTI & CIA LTDA',
							'SANGALETTI SANGALETTI CIA LTDA',
							'CASA AURORA CENTRO',
							'CM HOSPITALAR LTDA',
							'CM HOSPITALAR S/A',
							'DIPALMA COM DISTR LOGIST PROD ALIM LTDA',
							'BARCELOS E CIA LTDA',
							'GIRUS MERCANTIL DE ALIMENTOS LTDA',
							'BIG MART CENTRO DE COMPRAS LTDA',
							'BIG MART CENTRO DE COMPRAS LTDA LOJA 06 14877',
							'COOP CENTRAL DE COOP UNIMED RS LTDA',
							'DROGARIA ARAUJO S A',
							'JC DISTR MEDICAMENTOS LTDA',
							'JC DISTRIBUIDORA DE DIVISORIAS',
							'JC DISTRIBUIDORA EIRELI',
							'JC DISTRIBUIDORA IMPORTADORA E EXPORTADOEA EIRELI',
							'IRMAOS MUFFATO & CIA LTDA',
							'IRMAOS MUFFATO & CIA LTDA',
							'IRMAOS MUFFATO CIA LTDA',
							'IRMAOS MUFFATO E CIA LT'
				)
				and DMC02.REMETENTE NOT LIKE '%BR SUPPLY%'
			THEN 'SIM' 
			ELSE 'NAO'
			END ) AS AGENDAMENTOS
			,(CASE 
				when Agen3.DESCRICAO_OCOR IS NULL THEN 'SEM AGENDAMENTO'
				ELSE Agen3.DESCRICAO_OCOR 
			END) AS OCOR_AGENDAMENTO
			,avaria3.DESCRICAO_OCOR as ocorrencia_avaria
			,ISNULL(SO03.DESCRICAO_OCOR,'OUTROS') AS DESCRICAO_OCOR
			,SO03.FALHA_CLIENTE
			,DMFCE03.DT_EMISSAO_MANIFESTO
			,DMFCE03.DT_CHEGADA
			,DMFCE03.DT_BAIXA
			,DMFCE03.FIL_BAIXA_MNF
			,ISNULL(RomRed.DT_EMISS_ROM_RED,DRECE3.DT_EMISS_ROM_ENT) AS DT_EMISS_ROM
			,COALESCE(DEDICADOS.DEDICADO,'NAO') AS DEDICADO
			,DMC02.TIPO_FRETE
			,DMC02.TIPO_DOC
			,DMC02.VOL_MOV 
			,DMC02.PESO_MOV 
			,DMC02.PESO_CUBADO
			,DMC02.PESO_CUBADO_2
			,DMC02.nr_peso_cub_pad
			,DMC02.nr_peso_rel
			,DMC02.vl_dist_col_prop
			,DMC02.vl_dist_col_red
			,DMC02.vl_dist_ent_prop
			,DMC02.vl_dist_ent_red
			,DMC02.VLR_FRETE_TAB_PADRAO
			,DMC02.PERC_SEGURO_IOF
			,DMC02.PERC_RCF_DC
			,DMC02.ALIQ_INSS
			,DMC02.ALIQ_COFINS
			,DMC02.ALIQ_PIS
			,DMC02.VALOR_ICMS
			,DMC02.VALOR_ICMS_INCENTIVO
			,DMC02.COMISSAO_VENDAS
			,DMC02.FRETE
			,DMC02.DESCR_TIPO_TRANSP
			,DMC02.VENDEDOR
			,DMC02.SIGLA_FIL_DEST
			,(CASE 
				WHEN DMC02.SIGLA_FIL_DEST IN('ACR','BHZ','CPQ','ITA','RDN','SPO','UDI','PPY','EXT') THEN 'SPO'
				WHEN DMC02.SIGLA_FIL_DEST IN('BNU','ITJ','FLN') THEN 'ITJ'
				ELSE DMC02.SIGLA_FIL_DEST 
			END ) AS SIGLA_FIL_DEST_GROUP
			,DMC02.VAL_MERC_MOV
			,DMC02.PREVISAO_2 AS PREVISAO_ENTREGA 
			,COALESCE(SAC.nm_usuario,'SAC NORMAL') AS ATENDENTE
			,(CASE 
				WHEN DMC02.DT_ENTREGA is  null THEN 
					(DATEDIFF(dd,DMC02.PREVISAO_2 ,         GETDATE()))-(DATEDIFF(wk, DMC02.PREVISAO_2,         GETDATE()) * 2)
				ELSE		
					(DATEDIFF(dd,DMC02.PREVISAO_2 ,  DMC02.DT_ENTREGA))-(DATEDIFF(wk, DMC02.PREVISAO_2,  DMC02.DT_ENTREGA) * 2)
				END)	AS DIAS_ATRASO
			
			,DMC02.NR_ENTRADA
			,DMC02.DT_ATUALIZADO
		FROM
			(SELECT DISTINCT  
				 DMCE01.*
				,(CASE WHEN DATEPART(DW,PREVISAO_ENTREGA) = 7  THEN  DATEADD(DD,-1,PREVISAO_ENTREGA) ELSE PREVISAO_ENTREGA END) AS PREVISAO_2 
			FROM   tb_dados_movimento_custo_emis AS DMCE01 with(nolock)
			WHERE DMCE01.TIPO_DOC IN('NF','CO') 
				and DMCE01.PREVISAO_ENTREGA >DATEADD(DD,-60,GETDATE())
				and DMCE01.DT_ATUALIZADO = (select max(dmcsub.DT_ATUALIZADO) from tb_dados_movimento_custo_emis dmcsub where  dmcsub.SIGLA_FIL = DMCE01.SIGLA_FIL and dmcsub.NR_ENTRADA = DMCE01.NR_ENTRADA )
			)DMC02
		LEFT JOIN 
			(SELECT * FROM tb_dados_manifesto_custo_emis AS DMFCE01 with(nolock)
						WHERE  DMFCE01.COD_DADOS_MANIFESTO_CUSTO_EMIS = (SELECT MAX(DMFCE04.COD_DADOS_MANIFESTO_CUSTO_EMIS) FROM tb_dados_manifesto_custo_emis AS DMFCE04 WHERE DMFCE04.NR_ENTRADA = DMFCE01.NR_ENTRADA AND DMFCE04.SIGLA_FIL = DMFCE01.SIGLA_FIL)
			) AS DMFCE03 
			ON DMC02.NR_ENTRADA = DMFCE03.NR_ENTRADA AND DMC02.SIGLA_FIL = DMFCE03.SIGLA_FIL
		LEFT JOIN 
			(SELECT * FROM tb_valores_redespacho_custo_em DD with(nolock) WHERE TIPO_MANIFESTO = 'MRD'   ) AS VRCE 
			ON DMC02.NR_ENTRADA  = VRCE.NR_ENTRADA AND DMC02.SIGLA_FIL = VRCE.SIGLA_FIL
		LEFT JOIN
			( SELECT * FROM tb_dados_rom_entrega_custo_em DRECE2 with(nolock)  where 
					  DRECE2.COD_DADOS_ROM_ENTREGA_CUSTO_EM = (select max(DRECE1.COD_DADOS_ROM_ENTREGA_CUSTO_EM) from tb_dados_rom_entrega_custo_em DRECE1 where DRECE1.NR_ENTRADA = DRECE2.NR_ENTRADA AND DRECE1.SIGLA_FIL = DRECE2.SIGLA_FIL)
			) AS DRECE3
			ON DMC02.NR_ENTRADA = DRECE3.NR_ENTRADA AND DMC02.SIGLA_FIL = DRECE3.SIGLA_FIL
		LEFT JOIN
			(SELECT DISTINCT PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO FROM Tb_valores_contrato_custo with(nolock) ) AS VCC
			ON DRECE3.NUM_CONTRATO  = VCC.NUM_CONTRATO AND DRECE3.FIL_CONTRATO = VCC.FIL_CONTRATO
		LEFT JOIN 
			(SELECT * FROM tb_solid_dados_cliente AS SDC01 with(nolock)  WHERE SDC01.DT_INCL_CLI = (SELECT MAX(SDC02.DT_INCL_CLI) FROM tb_solid_dados_cliente AS SDC02 WHERE SDC02.CGC = SDC01.CGC) ) AS SDC03 
			ON DMC02.CGC_CONSIG = SDC03.CGC
		LEFT JOIN 
			(SELECT cli.nr_cnpj_cpf , (CASE WHEN part.tde2 = 1 THEN 'SIM' ELSE 'NAO' END) AS DEDICADO FROM tb_cliente cli with(nolock) INNER JOIN  tb_particularidades_cliente part with(nolock) ON part.cod_cliente = cli.cod_cliente) AS DEDICADOS
			ON DMC02.CGC_DEST =  DEDICADOS.nr_cnpj_cpf
		LEFT JOIN 		
			(select  distinct  cli.nr_cnpj_cpf , usu.nm_usuario from bd_portal_tsv.dbo.tb_usuario usu with(nolock) inner join bd_portal_tsv.dbo.tb_usuario_cliente uCli with(nolock) on uCli.id_usuario = usu.cod_user inner join bd_fin_tsv.dbo.tb_cliente cli with(nolock) on cli.cod_cliente  = uCli.id_cliente where usu.fl_status = 'A' and usu.funcao = 'ATENDENTE' and usu.ds_funcao = 'A'  and uCli.dt_cancela is null ) AS SAC 	
			ON DMC02.CGC_CONSIG = SAC.nr_cnpj_cpf 
	    LEFT JOIN
			(select distinct * from tb_dados_rom_redesp_custo_emi where TIPO_MANIFESTO = 'ENTREGA' ) as RomRed
			ON DMC02.SIGLA_FIL = RomRed.SIGLA_FIL and DMC02.NR_ENTRADA = RomRed.NR_ENTRADA
		LEFT JOIN 
			(SELECT  * FROM tb_solid_ocorrencias AS SO01 
										WHERE SO01.COD_SOLID_OCORRENCIAS = (SELECT MAX(SO02.COD_SOLID_OCORRENCIAS) FROM tb_solid_ocorrencias AS SO02 WHERE SO02.NR_ENTRADA = SO01.NR_ENTRADA AND SO02.SIGLA_FIL = SO01.SIGLA_FIL AND (SO02.FALHA_CLIENTE = 'S' OR SO02.FALHA_OPERACIONAL = 'S')  AND SO02.CODIGO_OCOR !=0  ) 
										AND (SO01.FALHA_CLIENTE = 'S' OR SO01.FALHA_OPERACIONAL = 'S')
										AND SO01.CODIGO_OCOR !=0
										

										
			)  AS SO03 
		ON DMC02.NR_ENTRADA = SO03.NR_ENTRADA AND DMC02.SIGLA_FIL = SO03.SIGLA_FIL
		LEFT JOIN 
			(SELECT * FROM tb_solid_ocorrencias AS Agen1  with(nolock)
										WHERE
										    Agen1.COD_SOLID_OCORRENCIAS = (SELECT max(Agen2.COD_SOLID_OCORRENCIAS) FROM tb_solid_ocorrencias AS Agen2 WHERE Agen2.NR_ENTRADA = Agen1.NR_ENTRADA AND Agen2.SIGLA_FIL = Agen1.SIGLA_FIL and Agen2.CODIGO_OCOR in(88,306,305,205,319,91) )
											and Agen1.CODIGO_OCOR in(88,306,305,205,319,91)
			) AS Agen3 
			ON DMC02.NR_ENTRADA = Agen3.NR_ENTRADA AND DMC02.SIGLA_FIL = Agen3.SIGLA_FIL
	 LEFT JOIN 
			(SELECT * FROM tb_solid_ocorrencias AS avaria1  with(nolock)
										WHERE
										    avaria1.COD_SOLID_OCORRENCIAS = (SELECT max(avaria2.COD_SOLID_OCORRENCIAS) FROM tb_solid_ocorrencias AS avaria2 WHERE avaria2.NR_ENTRADA = avaria1.NR_ENTRADA AND avaria2.SIGLA_FIL = avaria1.SIGLA_FIL and avaria2.CODIGO_OCOR in(5,30,33,62,119,143,202,204,11,78,120,201,202,204) )
											and avaria1.CODIGO_OCOR in(5,30,33,62,119,143,202,204,11,78,120,201,202,204)
			) AS avaria3 
			ON DMC02.NR_ENTRADA = avaria3.NR_ENTRADA AND DMC02.SIGLA_FIL = avaria3.SIGLA_FIL
	) AS TABELA 
	LEFT JOIN
		(select CIDADE, NOME_PARCEIRO, PRAZO_PARCEIRO from tb_redespacho_cidade with(nolock)) AS PRAZO
		ON TABELA.CIDADE_DESTINO = PRAZO.CIDADE AND TABELA.NOME_PROP = PRAZO.NOME_PARCEIRO
	
		