
SELECT DISTINCT 
	TABELA.* 
	,ISNULL(PRAZO.PRAZO_PARCEIRO,2) AS PRAZO_PARCEIRO
	,(CASE 	
		WHEN TABELA.STATUS_MOVIMENTO != 'REDESPACHO'  THEN 'UNIDADE' 
		WHEN Dias_Redespacho > ISNULL(PRAZO.PRAZO_PARCEIRO,2) then 'REDESPACHO'  else 'UNIDADE'
		END) AS Responsavel
	,(CASE 			
		WHEN TABELA.DIAS_OCORRENCIA BETWEEN  1 AND 14 THEN '1 A 14'	
		WHEN TABELA.DIAS_OCORRENCIA BETWEEN  15 AND 30 THEN '15 A 30' 
		WHEN TABELA.DIAS_OCORRENCIA >30 THEN ' > 30' 	
		WHEN TABELA.DIAS_OCORRENCIA = 0 THEN 'HOJE' 	
		ELSE 'NF DE SERVIÇO' 		
		END) AS FAIXA_OCORRENCIA 	
	,(CASE 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  1 AND 3 THEN '1 A 3' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  4 AND 6 THEN '4 A 6' 	
		WHEN TABELA.DIAS_ATRASO BETWEEN  7 AND 14 THEN '7 A 14' 
		WHEN TABELA.DIAS_ATRASO BETWEEN  15 AND 30 THEN '15 A 30' 
		WHEN TABELA.DIAS_ATRASO >30 THEN ' > 30' 
		when TABELA.DIAS_ATRASO = 0 and DATEPART(dw,  TABELA.PREVISAO_ENTREGA) = 7 then '1 A 3' 
		when TABELA.DIAS_ATRASO = 0 then 'HOJE'
		ELSE 'NO PRAZO' 
		END) AS FAIXA_ATRASO
	 ,(CASE
		WHEN TABELA.STATUS_ENTREGA = 'EM_ATRASO' THEN TABELA.NUM_DOC 
		END) AS DOC_ATRASADO
	 , GETDATE() AS ATUALIZACAO_PAINEL
	FROM	
			(SELECT DISTINCT 
			CONCAT( DMC02.SIGLA_FIL,' ', cast(DMC02.NUM_DOC as char)) AS NUM_DOC
			,DMC02.DATA_COLETA
			,DMC02.DT_EMISSAO
			,DMC02.DT_ENTREGA
			,DMC02.PREVISAO_ENTREGA
			,DMC02.NOTA_AGRUP AS NF
			,DMC02.REMETENTE
			,DMC02.DESTINATARIO
			,DMC02.CONSIGNATARIO
			,DMC02.LOCAL_ENTREGA
			,DMC02.CIDADE_DESTINO
			,DMC02.ESTADO_DESTINO
			,DMC02.ESTADO_DEST
			,DMC02.VAL_MERC_MOV
			,DMC02.SIGLA_FIL_DEST as RT3
			,(DATEDIFF(dd,RomRed.DT_EMISS_ROM_RED,  GETDATE()))-(DATEDIFF(wk, RomRed.DT_EMISS_ROM_RED, GETDATE()) * 2)-(CASE WHEN DATEPART(dw,  GETDATE()) = 1 THEN 1 ELSE 0 END)-(CASE WHEN DATEPART(dw, GETDATE()) = 7 THEN 1 ELSE 0 END) as Dias_Redespacho
			,(CASE 
				WHEN DMC02.RT4 = 'I' THEN 'INTERIOR' 
				WHEN DMC02.RT4 = 'C' THEN 'CAPITAL' 	
				ELSE 'INTERIOR 02' 	
				END) AS RT4
			,(CASE 			
				WHEN DMC02.ESTADO_DESTINO IN ('DF','GO','MS','MT') THEN 'Centro-Oeste'
				WHEN DMC02.ESTADO_DESTINO IN ('AL','BA','CE','MA','PB','PE','PI','RN','SE') THEN 'Nordeste' 
				WHEN DMC02.ESTADO_DESTINO IN ('AC','AM','AP','PA','RO','RR','TO') THEN 'Norte' 
				WHEN DMC02.ESTADO_DESTINO IN ('ES','MG','RJ','SP') THEN 'Sudeste' 	
				WHEN DMC02.ESTADO_DESTINO IN ('PR','RS','SC') THEN 'Sul' 		
				END) AS REGIAO
			,(CASE 	
				WHEN SDC03.DESCR_GRUPO_CLIENTE = '' THEN DMC02.CONSIGNATARIO 	
				WHEN SDC03.DESCR_GRUPO_CLIENTE IS NULL THEN DMC02.CONSIGNATARIO 
				ELSE SDC03.DESCR_GRUPO_CLIENTE  
				END) AS CLIENTE_GRUPO

			,(CASE 		
				WHEN VRCE.RAZAO IS NOT NULL THEN 'REDESPACHO' 
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL AND SO03.CODIGO_OCOR IN(104,67)  THEN 'ENTREGANDO'
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL AND SO03.CODIGO_OCOR IN(89)  THEN 'CT-E_RETIDO_NO_CLIENTE'
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL   THEN 'RETORNO '
				WHEN DMFCE03.NRO_MANIFESTO IS NULL THEN 'FIL ORIGEM'
				WHEN DMFCE03.DT_CHEGADA IS NULL THEN  'TRANSFERENCIA' 
				WHEN (substring(DMFCE03.NRO_MANIFESTO,5,3) = DMC02.RT3) THEN 'FIL DESTINO'
				WHEN (substring(DMFCE03.NRO_MANIFESTO,5,3) <> DMC02.RT3) THEN 'HUB'
				ELSE '-' END) AS STATUS_MOVIMENTO
			,(CASE 		
				WHEN VRCE.RAZAO IS NOT NULL THEN VRCE.RAZAO
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL AND SO03.CODIGO_OCOR IN(104,67)  THEN VCC.PLACA_PRINCIPAL
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL AND SO03.CODIGO_OCOR IN(89)  THEN DMC02.DESTINATARIO
				WHEN DRECE3.CPF_PROPRIETARIO IS NOT NULL   THEN SO03.DESCRICAO_OCOR
				WHEN DMFCE03.NRO_MANIFESTO IS NULL THEN DMC02.SIGLA_FIL
				WHEN DMFCE03.DT_CHEGADA IS NULL THEN substring(DMFCE03.NRO_MANIFESTO,5,3)
				WHEN (DMFCE03.FIL_BAIXA_MNF = DMC02.RT3) THEN DMC02.RT3
				WHEN (DMFCE03.FIL_BAIXA_MNF <> DMC02.RT3) THEN substring(DMFCE03.NRO_MANIFESTO,5,3)
				ELSE '-' END) AS NOME_PROP
			,SO03.CODIGO_OCOR
			,SO03.DESCRICAO_OCOR
			,SO03.DATA_OCORRENCIA
			,(CASE 				
				WHEN SO03.CODIGO_OCOR IN(1,2,62,84,94,100,117,119,120,121,301,303) AND DMC02.DT_ENTREGA IS NULL THEN 'SISTEMA' 	
				WHEN YEAR(DMC02.PREVISAO_ENTREGA) = 1900 THEN 'TABELA' 		
				WHEN SO03.FALHA_CLIENTE = 'S' THEN 'CLIENTE' 			
				ELSE 'OPERACIONAL' 				
				END) AS RESPONSABILIDADE 
			,(CASE 	 			
				WHEN SO03.CODIGO_OCOR IN(10) THEN 'COMERCIAL' 		
				WHEN SO03.CODIGO_OCOR IN(1,43,49,52,67,89,76,94,98,101,300,302,25,102) THEN 'CONTROL TOWER' 				
				WHEN SO03.CODIGO_OCOR IN(0,13,19,20,21,44,97,103,104) THEN 'DISTRIBUIÇÃO' 				
				WHEN SO03.CODIGO_OCOR IN(11,14,18,33,62,78,82,84,119,120,141,143,144,200,201,202,203,204) THEN 'Expedição/Operação' 		
				WHEN SO03.CODIGO_OCOR IN(116) THEN 'FINANCEIRO' 			
				WHEN SO03.CODIGO_OCOR IN(5,6,9,17,26,29,30,46,60,70,100,117,121,145,303,304,124) THEN 'PENDENCIA ADM' 		
				WHEN SO03.CODIGO_OCOR IN(61) THEN 'REVERSA' 					
				WHEN SO03.CODIGO_OCOR IN(4,2) THEN 'SAC' 		
				WHEN SO03.CODIGO_OCOR IN (88,91,205,305,306,319) THEN 'AGENDAMENTO'
				ELSE 'CONTROL TOWER' 				
				END) AS Sub_RESPONSABILIDADE 
			,DMFCE03.DT_EMISSAO_MANIFESTO
			,DMFCE03.DT_CHEGADA
			,DMFCE03.DT_BAIXA
			,DMFCE03.FIL_CONTRATO
			,DMFCE03.FIL_BAIXA_MNF
			,ISNULL(RomRed.DT_EMISS_ROM_RED,DRECE3.DT_EMISS_ROM_ENT) AS DT_EMISS_ROM
			,DRECE3.NRO_ROMANEIO_ENTREGA AS NRO_ROMANEIO_ENTREGA
			,VCC.NOME_MOT
			,COALESCE(DEDICADOS.DEDICADO,'NAO') AS DEDICADO
			,DMC02.TIPO_FRETE
			,DMC02.TIPO_DOC
			,DMC02.VOL_MOV AS VOLUMES
			,DMC02.PESO_CUBADO_2 AS PESO
			,DMC02.FRETE
			,DMC02.DESCR_TIPO_TRANSP
			,DMC02.VENDEDOR
			,DMC02.SIGLA_FIL_DEST
			,(CASE 
				WHEN DMC02.SIGLA_FIL_DEST IN('ACR','BHZ','CPQ','ITA','RDN','SPO','UDI','PPY','EXT') THEN 'SPO'
				WHEN DMC02.SIGLA_FIL_DEST IN('BNU','ITJ','FLN') THEN 'ITJ'
				ELSE DMC02.SIGLA_FIL_DEST 
			END ) AS SIGLA_FIL_DEST_GROUP
			,DMC02.CGC_CONSIG
			,COALESCE(SAC.nm_usuario,'SAC NORMAL') AS ATENDENTE
			,(CASE 
				WHEN DMC02.DT_ENTREGA is  null THEN 
					(DATEDIFF(dd,DMC02.PREVISAO_ENTREGA ,  GETDATE()))-(DATEDIFF(wk, DMC02.PREVISAO_ENTREGA,  GETDATE()) * 2)-(CASE WHEN DATEPART(dw,  GETDATE()) = 1 THEN 1 ELSE 0 END)-(CASE WHEN DATEPART(dw,  GETDATE()) = 7 THEN 1 ELSE 0 END) 
				ELSE		
					(DATEDIFF(dd,DMC02.PREVISAO_ENTREGA ,  DMC02.DT_ENTREGA))-(DATEDIFF(wk, DMC02.PREVISAO_ENTREGA,  DMC02.DT_ENTREGA) * 2)-(CASE WHEN DATEPART(dw,  DMC02.DT_ENTREGA) = 1 THEN 1 ELSE 0 END)-(CASE WHEN DATEPART(dw,  DMC02.DT_ENTREGA) = 7 THEN 1 ELSE 0 END) 
				END)	AS DIAS_ATRASO
			,(DATEDIFF(dd,SO03.DATA_OCORRENCIA,  GETDATE()))-(DATEDIFF(wk, SO03.DATA_OCORRENCIA, GETDATE()) * 2)-(CASE WHEN DATEPART(dw,  GETDATE()) = 1 THEN 1 ELSE 0 END)-(CASE WHEN DATEPART(dw, GETDATE()) = 7 THEN 1 ELSE 0 END) AS DIAS_OCORRENCIA
			,(CASE             
				WHEN DMC02.DT_ENTREGA is  null THEN 
					(CASE
						WHEN (DATEDIFF(dd,DMC02.PREVISAO_ENTREGA ,  GETDATE()) ) <= 0 THEN 'EM_ABERTO'  ELSE 'EM_ATRASO'  
						END)
				ELSE 
					(CASE
						WHEN (DATEDIFF(dd,DMC02.PREVISAO_ENTREGA ,  DMC02.DT_ENTREGA) ) <= 0 THEN 'NO_PRAZO'  ELSE 'ATRAZADO'  
						END)
				END) AS STATUS_ENTREGA
			,DMC02.NR_ENTRADA
		FROM
			(SELECT DISTINCT  dbo.fn_ret_notas_cte(DMCE01.NR_ENTRADA, DMCE01.SIGLA_FIL) AS NOTA_AGRUP , DMCE01.* FROM   tb_dados_movimento_custo_emis  AS DMCE01  with(nolock) WHERE DMCE01.TIPO_DOC IN('NF','CO') AND DMCE01.DT_EMISSAO >= '20200501' AND DMCE01.DT_ENTREGA IS NULL and DMCE01.DESTINATARIO 
			in
			(
			'RAIA DROGASIL S A',
			'RAIA DROGASIL S.A',
			'RAIA DROGASIL S.A.',
			'RAIA DROGASIL S/A',
			'RAIA DROGASIL S/A - LOJA 712 CAMPO GRANDE AFONSO P',
			'RAIA DROGASIL S/A - LOJA 713 CAMPO GRANDE 13 DE JU',
			'RAIA DROGASIL S/A - LOJA 714',
			'RAIA DROGASIL S/A - LOJA 723 DOURADOS',
			'RAIA DROGASIL S/A - LOJA 739 - SHOPPING CAMPO GRAN',
			'RAIA DROGASIL S/A- 1019R EUSTAQUIO B (PE EUSTAQUIO',
			'RAIA DROGASIL S/A-1326D - GO JD NOVO MUNDO',
			'RAIA DROGASIL SA',
			'RAIA DROGASIL/SA.',
			'DROGARIA PACHECO S.A.',
			'DROGARIA PACHECO SA',
			'PANPHARMA DIST DE MEDICAMENTO LTDA',
			'PANPHARMA DIST DE MEDICAMENTOS LTDA',
			'PANPHARMA DISTRIB DE MEDICAMENTOS LTDA',
			'PANPHARMA DISTRIBUIDOR,A DE MEDICAMENTOS, LTDA',
			'PANPHARMA DIT DE MEDICAMENTOS LTDA',
			'SENDAS DIST. S A',
			'SENDAS DISTRIBUIDORA',
			'SENDAS DISTRIBUIDORA S A',
			'SENDAS DISTRIBUIDORA S.A',
			'SENDAS DISTRIBUIDORA S.A.',
			'SENDAS DISTRIBUIDORA S/A',
			'SENDAS DISTRIBUIDORA SA',
			'SENDAS DISTRIBUIDORA SA LOJA 102',
			'SENDAS DISTRIBUIDORA SA LOJA 57',
			'SENDAS DISTRIBUIDORA SA LOJA 70',
			'DISTR. DE MED STA CRUZ LTDA',
			'SDB COM DE ALIMENTOS LTDA',
			'SDB COMERCIO DE ALIMENTOS LTDA',
			'SDB COMERCIO DE ALIMENTOS LTDA (FORT AREAO - MT)',
			'SDB COMERCIO DE ALM LTDA (FORT TAGUATINGA - DF)',
			'SDB METERIG SISTEMAS DE MEDICAO LTDA',
			'DIST MEDICAMENTOS STA CRUZ LTDA',
			'DISPAR DISTRIBUIDORA DE MEDICAMENTOS LTDA',
			'VENANCIO PRODS FARMAC LTDA',
			'VENANCIO PRODUTOS FARMACEUTICOS LTDA',
			'VENANCIO PRODUTOS FARMACEUTICOS LTD',
			'VENANCIO PRODUTOS FARMACEUTICOS LTDA',
			'CARREFOUR COM IND LTDA',
			'CARREFOUR COM INDUSTRIA LTDA',
			'CARREFOUR COMERCIO E INDUSTRIA LTDA',
			'ATACADAO S A 47791',
			'ATACADAO BARATAO LTDA',
			'ATACADAO COMERCIO DE GENEROS ALIMENTICIOS LTDA',
			'ATACADAO COMERCIO DE PECAS AGRICOLAS',
			'ATACADAO DA CONSTRUCAO LTDA',
			'ATACADAO DA PROTEÇÃO IND E COMERCIO EQUIPAMENTOS',
			'ATACADAO DA RACAO COMERCIO DE PRODUTOS AGROPECUARI',
			'ATACADAO DAS BATERIAS LTDA',
			'ATACADAO DAS EMBALAGENS EIRELI',
			'ATACADAO DIST COM E IND LTDA',
			'ATACADAO DIST COM E INDUSTRIA LTDA',
			'ATACADAO DIST COM IND LTDA',
			'ATACADAO DIST COMERCIO E INDUSTRIA LTDA',
			'ATACADAO DISTB LTDA',
			'ATACADAO DISTR COM E IND LTDA',
			'ATACADAO DISTR COM IND LTDA',
			'ATACADAO DISTR COM IND. LTDA 30',
			'ATACADAO DISTR.COM. E IND. LTDA',
			'ATACADAO DISTR.COMERCIO E INDUSTRIA LTDA',
			'ATACADAO DISTRIB COM E IND LTDA',
			'ATACADAO DISTRIBUICAO COM E IND LTDA',
			'ATACADAO DISTRIBUICAO COM IND LTDA',
			'ATACADAO DISTRIBUICAO COM LTDA',
			'ATACADAO DISTRIBUICAO COMERCIO E IND LTDA',
			'ATACADAO DISTRIBUICAO COMERCIO E INDUSTRIA LTDA',
			'ATACADAO DISTRIBUIDORA COMERCIO E IND LTDA',
			'ATACADAO DISTRUICAO COM INDUSTRIA LTDA',
			'ATACADAO DO BEBE IND E COM DE CONF EIRELI',
			'ATACADAO DO RECUPERADOR (MARCOS P. M. DE SOUZA ME)',
			'ATACADAO MOTO PECAS LTDA',
			'ATACADAO MOTO PECAS LTDA - ME',
			'ATACADAO MOTO PEÇAS LTDA EPP',
			'ATACADAO PAPELEX LTDA',
			'ATACADAO S A',
			'ATACADAO S A 1525',
			'ATACADAO S A 36179',
			'ATACADAO S A 36188',
			'ATACADAO S A 37613',
			'ATACADAO S A 43025',
			'ATACADAO S A 63168',
			'ATACADAO S A 9684',
			'ATACADAO S A 9686',
			'ATACADAO S.A',
			'ATACADAO S.A 70650',
			'ATACADAO S.A.',
			'ATACADAO S/ A LJ202 - RJ',
			'ATACADAO S/A',
			'ATACADAO S/A.(LJ.174)',
			'ATACADAO S/A.(LJ.193)',
			'ATACADAO SA',
			'EMPREEMDIMENTOS PAGUE MENOS SA',
			'EMPREENDIMENTOS PAGUE MENOS',
			'EMPREENDIMENTOS PAGUE MENOS S A',
			'EMPREENDIMENTOS PAGUE MENOS S.A',
			'EMPREENDIMENTOS PAGUE MENOS S/A',
			'EMPREENDIMENTOS PAGUE MENOS SA',
			'PAGUE MENOS COM DE PROD ALIM LTDA *',
			'DROGARIA SAO PAULO S.A',
			'DROGARIA SAO PAULO S.A.',
			'DROGARIA SAO PAULO S/A',
			'DROGARIA SAO PAULO SA',
			'B2M ACATAREJO DO BRASIL LTDA',
			'B2M ATACAREJO DO BRASIL LTDA',
			'B2M ATACAREJOS DO BRASIL LTDA',
			'FARMACIA E DROGARIA NISSEI LTDA',
			'FARMACIA E DROGARIA NISSEI S A',
			'FARMACIA E DROGARIA NISSEI S/A',
			'DIMED S A DISTRIBUIDORA DE MEDICAM',
			'DIMED A DISTRIBUIDORA DE MEDICAM',
			'DIMED COM PREST SERVS LTDA',
			'DIMED S A DISTRIBUIDORA DE MEDICAM',
			'DIMED S/A DISTRIBUIDORA DE MEDICA',
			'DIMED SA DISTRIB DE MEDICAMENTOS',
			'DIMED SA DISTRIBUIDORA DE MEDICAMENTOS',
			'INTITUTO DE MEDICINA DIGITAL DIMEDI LTD',
			'CENTRO OESTE COM DE ALIM LTDA',
			'CENTRO OESTE COM LUBRIFICANTES LTDA',
			'CENTRO OESTE COMERCIAL DE ALIMENTOS LTDA',
			'CENTRO OESTE COM.ATAC.E VAREJ.DE COSEM.',
			'CENTRO OESTE COML DE ALIMENTOS EIRELI',
			'CENTRO OESTE COML DE ALIMENTOS LTDA',
			'PROFARMA DIST DE PRODS FARM SA',
			'PROFARMA DIST PRODS FARMACEUTICOS S A',
			'PROFARMA DISTR DE PRODS FARM S/A',
			'PROFARMA DISTR DE PRODS FARM SA',
			'PROFARMA DISTRIB DE PROD FARM SA',
			'PROFARMA DISTRIB DE PROD FARMAC S/A',
			'DEL MORO & DEL MORO',
			'DEL MORO & DEL MORO LTDA',
			'DEL MORO AMP AMP DEL MORO LTDA',
			'DEL MORO DEL MORO LTDA',
			'DEL MORO E DEL MORO LTDA',
			'GAZIN ATACADO CENTRO-OESTE LTDA',
			'GAZIN IND E COM DE MOVEIS E ELETROD LTDA',
			'GAZIN INFORMATICA LTDA',
			'CIA BRASILEIRA DE DISTRIBUICAO',
			'COMPANHIA BRASILEIRA DE DISTRIBUICA',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO 1018',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO1418',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO1635',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO1813',
			'COMPANHIA BRASILEIRA DE DISTRIBUICAO5267',
			'COMPANHIA BRASILEIRA DE DISTRIBUIÇÃ',
			'COMPANIA BRASILEIRA DE DISTRIBUIÇÃO',
			'EMPRESA BRASILEIRA DE DISTB LTDA',
			'STO ATACADISTA DE ALIMENTOS EIRELI',
			'PEROLA DISTRIBUICAO E LOGISTICA LTDA',
			'A B V COM DE ALIM LTDA',
			'SANGALETTI SANGALETTI & CIA LTDA',
			'SANGALETTI SANGALETTI CIA LTDA',
			'CASA AURORA CENTRO',
			'CM HOSPITALAR LTDA',
			'CM HOSPITALAR S/A',
			'DIPALMA COM DISTR LOGIST PROD ALIM LTDA',
			'BARCELOS E CIA LTDA',
			'GIRUS MERCANTIL DE ALIMENTOS LTDA',
			'BIG MART CENTRO DE COMPRAS LTDA',
			'BIG MART CENTRO DE COMPRAS LTDA LOJA 06 14877',
			'COOP CENTRAL DE COOP UNIMED RS LTDA',
			'DROGARIA ARAUJO S A',
			'JC DISTR MEDICAMENTOS LTDA',
			'JC DISTRIBUIDORA DE DIVISORIAS',
			'JC DISTRIBUIDORA EIRELI',
			'JC DISTRIBUIDORA IMPORTADORA E EXPORTADOEA EIRELI',
			'IRMAOS MUFFATO & CIA LTDA',
			'IRMAOS MUFFATO & CIA LTDA',
			'IRMAOS MUFFATO CIA LTDA',
			'IRMAOS MUFFATO E CIA LT'
			)) DMC02
		LEFT JOIN 
			(SELECT * FROM tb_solid_ocorrencias AS SO01  with(nolock)
										WHERE SO01.DATA_OCORRENCIA = (SELECT MAX(SO02.DATA_OCORRENCIA) FROM tb_solid_ocorrencias AS SO02 WHERE SO02.NR_ENTRADA = SO01.NR_ENTRADA AND SO02.SIGLA_FIL = SO01.SIGLA_FIL ) and SO01.DATA_OCORRENCIA > '20200101' 
										AND   SO01.CODIGO_OCOR = (SELECT MIN(SO02.CODIGO_OCOR) FROM tb_solid_ocorrencias AS SO02 WHERE SO02.NR_ENTRADA = SO01.NR_ENTRADA AND SO02.SIGLA_FIL = SO01.SIGLA_FIL 
															     AND SO02.DATA_OCORRENCIA = (SELECT MAX(SO04.DATA_OCORRENCIA) FROM tb_solid_ocorrencias AS SO04 WHERE SO04.NR_ENTRADA = SO02.NR_ENTRADA AND SO04.SIGLA_FIL = SO02.SIGLA_FIL )
																)
			) AS SO03 
			ON DMC02.NR_ENTRADA = SO03.NR_ENTRADA AND DMC02.SIGLA_FIL = SO03.SIGLA_FIL
		LEFT JOIN 
			(SELECT * FROM tb_dados_manifesto_custo_emis AS DMFCE01  with(nolock)
										WHERE DMFCE01.DT_EMISSAO_MANIFESTO = (SELECT MAX(DMFCE02.DT_EMISSAO_MANIFESTO) FROM tb_dados_manifesto_custo_emis AS DMFCE02 WHERE DMFCE02.NR_ENTRADA = DMFCE01.NR_ENTRADA AND DMFCE02.SIGLA_FIL = DMFCE01.SIGLA_FIL ) AND DMFCE01.DT_EMISSAO_MANIFESTO >'20200101'
										AND  DMFCE01.COD_DADOS_MANIFESTO_CUSTO_EMIS = (SELECT MAX(DMFCE04.COD_DADOS_MANIFESTO_CUSTO_EMIS) FROM tb_dados_manifesto_custo_emis AS DMFCE04 WHERE DMFCE04.NR_ENTRADA = DMFCE01.NR_ENTRADA AND DMFCE04.SIGLA_FIL = DMFCE01.SIGLA_FIL 
																	AND  DMFCE04.DT_EMISSAO_MANIFESTO = (SELECT MAX(DMFCE05.DT_EMISSAO_MANIFESTO) FROM tb_dados_manifesto_custo_emis AS DMFCE05 WHERE DMFCE05.NR_ENTRADA = DMFCE04.NR_ENTRADA AND DMFCE05.SIGLA_FIL = DMFCE04.SIGLA_FIL )
																				)
			) AS DMFCE03 
			ON DMC02.NR_ENTRADA = DMFCE03.NR_ENTRADA AND DMC02.SIGLA_FIL = DMFCE03.SIGLA_FIL
		LEFT JOIN 
			(SELECT * FROM tb_valores_redespacho_custo_em  with(nolock) WHERE TIPO_MANIFESTO = 'MRD') AS VRCE
			ON DMC02.NR_ENTRADA  = VRCE.NR_ENTRADA AND DMC02.SIGLA_FIL = VRCE.SIGLA_FIL
		LEFT JOIN
			( SELECT * FROM tb_dados_rom_entrega_custo_em DRECE2  with(nolock)  where 
					DRECE2.DT_EMISS_ROM_ENT = (select max(DRECE1.DT_EMISS_ROM_ENT) from tb_dados_rom_entrega_custo_em DRECE1 where DRECE1.NR_ENTRADA = DRECE2.NR_ENTRADA AND DRECE1.SIGLA_FIL = DRECE2.SIGLA_FIL )
					 AND DRECE2.NRO_ROMANEIO_ENTREGA = (select max(DRECE1.NRO_ROMANEIO_ENTREGA) from tb_dados_rom_entrega_custo_em DRECE1 where DRECE1.NR_ENTRADA = DRECE2.NR_ENTRADA AND DRECE1.SIGLA_FIL = DRECE2.SIGLA_FIL AND DRECE2.DT_EMISS_ROM_ENT = (select max(DRECE1.DT_EMISS_ROM_ENT) from tb_dados_rom_entrega_custo_em DRECE1 where DRECE1.NR_ENTRADA = DRECE2.NR_ENTRADA AND DRECE1.SIGLA_FIL = DRECE2.SIGLA_FIL )  )
			) AS DRECE3
			ON DMC02.NR_ENTRADA = DRECE3.NR_ENTRADA AND DMC02.SIGLA_FIL = DRECE3.SIGLA_FIL
		LEFT JOIN
			(SELECT DISTINCT PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO , NOME_MOT FROM Tb_valores_contrato_custo  with(nolock) WHERE DT_EMIS_CONTRATO > '20200101') AS VCC
			ON DRECE3.NUM_CONTRATO  = VCC.NUM_CONTRATO AND DRECE3.FIL_CONTRATO = VCC.FIL_CONTRATO
		LEFT JOIN 
			(SELECT * FROM tb_solid_dados_cliente AS SDC01  with(nolock) WHERE SDC01.DT_INCL_CLI = (SELECT MAX(SDC02.DT_INCL_CLI) FROM tb_solid_dados_cliente AS SDC02 WHERE SDC02.CGC = SDC01.CGC)) AS SDC03 
			ON DMC02.CGC_CONSIG = SDC03.CGC
	
		LEFT JOIN 
			(SELECT cli.nr_cnpj_cpf , (CASE WHEN part.tde2 = 1 THEN 'SIM' ELSE 'NAO' END) AS DEDICADO FROM tb_cliente cli  with(nolock) INNER JOIN  tb_particularidades_cliente part  with(nolock) ON part.cod_cliente = cli.cod_cliente) AS DEDICADOS
			ON DMC02.CGC_DEST =  DEDICADOS.nr_cnpj_cpf

		LEFT JOIN 		
			(select  distinct  cli.nr_cnpj_cpf , usu.nm_usuario from bd_portal_tsv.dbo.tb_usuario usu  with(nolock) inner join bd_portal_tsv.dbo.tb_usuario_cliente uCli  with(nolock) on uCli.id_usuario = usu.cod_user inner join bd_fin_tsv.dbo.tb_cliente cli  with(nolock) on cli.cod_cliente  = uCli.id_cliente where usu.fl_status = 'A' and usu.funcao = 'ATENDENTE' and usu.ds_funcao = 'A'  and uCli.dt_cancela is null ) AS SAC 	
			ON DMC02.CGC_CONSIG = SAC.nr_cnpj_cpf 
		 LEFT JOIN
			(select distinct * from tb_dados_rom_redesp_custo_emi where TIPO_MANIFESTO = 'ENTREGA' and DT_EMISS_ROM_RED > '20200101') as RomRed
			ON DMC02.SIGLA_FIL = RomRed.SIGLA_FIL and DMC02.NR_ENTRADA = RomRed.NR_ENTRADA
	) AS TABELA
	LEFT JOIN
	(select CIDADE, NOME_PARCEIRO, PRAZO_PARCEIRO from tb_redespacho_cidade) AS PRAZO
	ON TABELA.CIDADE_DESTINO = PRAZO.CIDADE AND TABELA.NOME_PROP = PRAZO.NOME_PARCEIRO



