
SELECT DMCE.NUM_DOC,DMCE.TIPO_DOC,DMCE.FRETE,VCC.VALOR_CONTRATO, (DMCE.FRETE - VCC.VALOR_CONTRATO) AS RECEITA FROM tb_dados_movimento_custo_emis AS DMCE 
LEFT JOIN
tb_dados_rom_entrega_custo_em AS DRECE
ON DMCE.NR_ENTRADA = DRECE.NR_ENTRADA AND DMCE.SIGLA_FIL = DRECE.SIGLA_FIL
LEFT JOIN
( SELECT PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO, sum(VALOR_CONTRATO) as VALOR_CONTRATO FROM  Tb_valores_contrato_custo group by PLACA_PRINCIPAL, FIL_CONTRATO ,NUM_CONTRATO) AS VCC
ON DRECE.NUM_CONTRATO  = VCC.NUM_CONTRATO AND DRECE.FIL_CONTRATO = VCC.FIL_CONTRATO
WHERE DMCE.DT_EMISSAO > '20200629'
ORDER BY VCC.VALOR_CONTRATO DESC


